language: generic
matrix:
  include:
    - script:
        - xcodebuild -scheme Yams build-for-testing test-without-building # -sdk macosx -destination arch=x86_64
        - xcodebuild -scheme Yams build-for-testing test-without-building -sdk iphonesimulator -destination "name=iPhone 6s"
        - xcodebuild -scheme Yams build-for-testing test-without-building -sdk appletvsimulator -destination "name=Apple TV 1080p"
        - xcodebuild -scheme Yams build -sdk watchsimulator -destination "name=Apple Watch - 38mm"
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.2
      before_install:
        - xcrun simctl delete BE8E0914-5B5F-45C2-8C99-879894AF72B0
    - script:
        - swift test
        - swiftlint
      env: JOB=SPM
      os: osx
      osx_image: xcode8.2
    - script: docker run -v `pwd`:/Yams norionomura/sourcekit:302 bash -c "cd /Yams && swift test"
      env: JOB=Linux
      sudo: required
      services: docker
notifications:
  email: false
